name: Docker CI/CD

on:
  schedule:
    # Run this workflow at 00:00 on every Monday
    - cron: "0 0 * * MON"
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build and publish Taswira
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        # It will push the image to ghcr.io/moja-global/taswira:master on push
        with:
          images: ${{ env.REGISTRY }}/moja-global/taswira

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          # Prevent push to GHCR on pull requests
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Implement Docker build caching for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
